//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
	public class Celula
	{

		private Vector3 posicion;
		private int identificador;
			

		public Celula (Vector3 pos,int id)
		{
			posicion = pos;
			identificador = id;


		}

		public Vector3 m_posicion
		{
			get { return posicion; }
			set { posicion = value; }
		}	

		public int m_identificador
		{
			get { return identificador; }
			set { identificador = value; }
		}
}


