//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
namespace AssemblyCSharp
{
	public class EstadoTutorial
	{

		public GameObject objeto;
		public GameObject flecha;
		public String texto;


		public EstadoTutorial (GameObject flecha, GameObject objeto, String texto)
		{
			this.objeto = objeto;
			this.flecha = flecha;
			this.texto = texto;
		}

		public void Activar(int numero,Text texto){


		}
	}
}

